version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: 'postgres_db'
      POSTGRES_USER: 'db_user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
